sudo: false

dist: trusty

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt

language: scala
scala: 2.11.8
jdk: oraclejdk8

services:
  - docker

before_install:
  - docker pull neo4j
  - docker run -d --publish=7687:7687 --env=NEO4J_AUTH=none neo4j:3.0

after_success:
  - docker stop $(docker ps -a -q)
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in secring.gpg.enc -out local.secring.gpg -d
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in pubring.gpg.enc -out local.pubring.gpg -d
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in credentials.sbt.enc -out local.credentials.sbt -d

## Implement when deployment is ready
#  - >
#    test "${TRAVIS_PULL_REQUEST}" = 'false' && test "${TRAVIS_JDK_VERSION}" = 'oraclejdk7' -o "${TRAVIS_SCALA_VERSION}" = '2.12.0-M5' &&
#    sbt 'set resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"'
#    'set credentials += Credentials("Sonatype Nexus Repository Manager", "oss.sonatype.org", System.getenv("SONATYPE_USER"), System.getenv("SONATYPE_PASS"))'
#    ++${TRAVIS_SCALA_VERSION}
#    publish

after_failure:
  - docker stop $(docker ps -a -q)

branches:
  only:
    - master

## Implement when deployment is ready
#env:
#  global:
#    - secure: ""
#    - secure: ""