language: scala

scala:
  - 2.11.8

jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - docker pull neo4j
  - docker run -d --env=NEO4J_AUTH=none neo4j:3.0

after_success:
  - docker stop $(docker ps -a -q)

after_failure:
  - docker stop $(docker ps -a -q)