language: scala

scala:
  - 2.11.8

jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - docker pull neo4j
  - docker run -d neo4j:2.3 --env=NEO4J_AUTH=none

after_success:
  - docker stop $(docker ps -a -q)

after_failure:
  - docker stop $(docker ps -a -q)